export const ON_PLAYLIST = 'ON_PLAYLIST';
export const ON_PROFILE = 'ON_PROFILE';
export const ON_PLAYLIST_SONGS = 'ON_PLAYLIST_SONGS';
export const ON_LOGOUT = 'ON_LOGOUT';
export const ON_PLAYLIST_ERROR = 'ON_PLAYLIST_ERROR';
export const ON_PROFILE_ERROR = 'ON_PROFILE_ERROR';
export const ON_PLAYLIST_SONGS_ERROR = 'ON_PLAYLIST_SONGS_ERROR';
export const ON_LOGOUT_ERROR = 'ON_LOGOUT_ERROR';
